[package]
name = "amg_match"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Research iterative solver utilities"
repository = "https://github.com/aujxn/amg_match"
readme = "README.md"

[dependencies]
nalgebra = { version = "0", features = ["rand"] }
nalgebra-sparse = { version = "0.9", features = ["io", "serde-serialize"] }
image = "0"
indexmap = "1"
rand = "0"
structopt = "0"
pretty_env_logger = "0"
log = "0"
strum = "0"
strum_macros = "0"
rayon = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0"
plotters = "0.3.3"
#vtkio = "0.6.3"
# TODO add anyhow and fix all error handling

#[dependencies.nalgebra-lapack]
#version = "0"

[dev-dependencies]
test-generator = "0"
# TODO write lots of tests

[profile.release]
debug = true
