[package]
name = "amg_match"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0", features = ["rand"] }
nalgebra-sparse = { version = "0", features = ["io"] }
image = "0"
indexmap = "1"
rand = "0"
structopt = "0"
pretty_env_logger = "0"
log = "0"
strum = "0"
strum_macros = "0"
rayon = "1"
reqwest = { version = "0", features = ["stream", "gzip"] }
soup = "0"
flate2 = "1"
tar = "0"
tokio = { version = "1", features = ["full"] }
plotly = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# TODO add anyhow and fix all error handling

[dependencies.nalgebra-lapack]
version = "0"

[dev-dependencies]
test-generator = "0"
# TODO write lots of tests

[profile.release]
debug = true
