[package]
name = "amg_match"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.30.1", features = ["rand"] }
nalgebra-sparse = { version = "0.6.0", features = ["io"] }
image = "0.24.1"
indexmap = "1.8.0"
rand = "0.8.5"
structopt = "0.3.26"
pretty_env_logger = "0.4.0"
log = "0.4.16"
strum = "0.24"
strum_macros = "0.24"

[dev-dependencies]
test-generator = "0.3.0"
