[package]
name = "amg_match"
version = "0.1.0"
edition = "2021"

[dependencies]
sprs = "0.11.0"
ndarray = "0.15.4"
ndarray-rand = "0.14.0"
ndarray-linalg = {version = "0.14.1", features = ["openblas-system"]}
image = "0.24.1"
indexmap = "1.8.0"
rand = "0.8.5"
structopt = "0.3.26"
pretty_env_logger = "0.4.0"
log = "0.4.16"
strum = "0.24"
strum_macros = "0.24"
